"""empty message

Revision ID: 420b7efec0dd
Revises: ec400253c019
Create Date: 2020-07-04 13:03:58.600330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420b7efec0dd'
down_revision = 'ec400253c019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genre', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genre')
    # ### end Alembic commands ###
