"""empty message

Revision ID: 848d5cea4afc
Revises: 86b5f346f23e
Create Date: 2020-07-10 15:11:48.241862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '848d5cea4afc'
down_revision = '86b5f346f23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_time', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'show_tim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_tim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'show_time')
    # ### end Alembic commands ###
