"""empty message

Revision ID: 86b5f346f23e
Revises: 06f8ce1179ed
Create Date: 2020-07-10 15:11:17.244327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86b5f346f23e'
down_revision = '06f8ce1179ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_tim', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'show_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'show_tim')
    # ### end Alembic commands ###
